title: goiabada/docs
description: Containing all sweet info about Goiabada's projects
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md